version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/create-db.sql
      - ./db/volume:/var/lib/postgresql/data
  cache:
    image: redis:alpine
    restart: on-failure
    hostname: localhost
    ports:
      - '6379:6379'
volumes:
  db:
    driver: local
